gomanifest/build.go
gomanifest/internal/deps.go
gomanifest/internal/deps_test.go
gomanifest/internal/manifest.go

Resolved lint errors to enable github action with lint.

fix: [APPAI-1597] Resolved go lint errors

---

gomanifest/internal/manifest.go
gomanifest/internal/manifest_test.go

Added support for 'replace' directive as per jira ticket: https://issues.redhat.com/browse/APPAI-1620

feat: [APPAI-1620] Add support for 'replace' directive

---

README.md

Readme update with more details.

chore: Added more details to readme

---

.github/workflows/ci-build.yml
README.md

added action that generates our code report on https://goreportcard.com/ and a corresponding badge to it .

chore: Add Go report action badge 

---

analyses/maven/matcher.go
analyses/maven/matcher_test.go
analyses/maven/maven.go
analyses/maven/testdata/pom.xml
analyses/pypi/matcher.go
analyses/stackanalyses/controller.go

CRDA CLI: Analyse Command - Java/Maven
Build: `go build -o crda`
Cmd:
```
./crda analyse /
--file /home/deepshar/projects/go/src/cli-tools/pom.xml          # Absolute Path of Manifest File
--debug # Optional
```

feat: crda cli: Analyse command - maven

---

README.md
docs/cli_README.md
docs/gomanifest.md

Readme Update, Added CRDA CLI Wiki.

---

analyses/golang/matcher.go
analyses/golang/matcher_test.go
analyses/stackanalyses/controller.go
cmd/analyse.go
cmd/root.go
gomanifest/build.go
gomanifest/generator/deps.go
gomanifest/generator/deps_test.go
gomanifest/generator/golist.go
gomanifest/generator/manifest.go
gomanifest/generator/manifest_test.go

CRDA CLI: Analyse Command - Golang
Build: `go build -o crda`
Cmd:
```
./crda analyse /
--file /home/deepshar/projects/go/src/cli-tools/go.mod         # Absolute Path of Manifest File
--debug # Optional
```

feat: crda cli: Analyse command - golang

---

analyses/npm/matcher.go
analyses/npm/matcher_test.go
analyses/npm/testdata/package.json
analyses/stackanalyses/controller.go

CRDA CLI: Analyse Command - NPM
Build: `go build -o crda`
Execute:
```
./crda analyse --file /absolute/path/to/package.json 
```
Development Run
```
go run main.go analyse --file /absolute/path/to/package.json 
```

feat: crda cli: Analyse command - npm 

---

analyses/driver/matcher.go
analyses/summary/helper_test.go
analyses/summary/helpers.go
cmd/analyse.go
cmd/auth.go
cmd/root.go
utils/constants.go

- Update Url, 3Scale constants to Prod.
- Few Typos fix
- Moved `synk-token` flag to under `auth` command. 
- Fixes Issue in calculating Transitive Vulnerabilities

fix: include transitive vulns and fix typos

---

cmd/analyse.go
cmd/auth.go
cmd/root.go
docs/cli_README.md

Jenkins server is having conflicts in setting kebab case variables as env variables.
This fix updates compatible env variables casing support to snake case.

fix: updating env variables casing support from kebab-case to snake_case

---

docs/cli_README.md

Update Readme to reflect correct behaviour

chore: readme update

---

utils/api.go

fix: make host and port overridable

---

.goreleaser.yml
docs/cli_README.md

fix: minor readme and release job fix

---

analyses/stackanalyses/controller.go
gomanifest/generator/deps.go
gomanifest/generator/manifest.go

Closes https://github.com/fabric8-analytics/cli-tools/issues/55

fix: Handling Auth Error

---

analyses/driver/matcher.go
analyses/stackanalyses/controller.go
pkg/telemetry/telemetry.go

Closes: https://issues.redhat.com/browse/APPAI-1876 
Closes: https://issues.redhat.com/browse/APPAI-1824

fix: minor grammar fixes

---

analyses/driver/matcher.go
analyses/stackanalyses/controller.go
auth/server.go
cmd/analyse.go
cmd/auth.go
pkg/telemetry/telemetry.go
utils/api.go

Add `client` header in each http request to crda server
Closes: https://issues.redhat.com/browse/APPAI-1875

feat: add client header in each http request to crda server

---

Makefile
docs/cli_README.md
pkg/config/viper_config.go
pkg/config/viper_config_test.go

Fixes https://issues.redhat.com/browse/APPAI-1828

fix: unable to bind env variables

---

cmd/analyse.go
cmd/root.go
pkg/analyses/driver/matcher.go
pkg/analyses/golang/matcher.go
pkg/analyses/maven/matcher.go
pkg/analyses/npm/matcher.go
pkg/analyses/pypi/matcher.go
pkg/analyses/stackanalyses/controller.go
pkg/analyses/summary/helpers.go
pkg/analyses/summary/types.go
pkg/utils/api.go
pkg/utils/constants.go

Ignore Vulnerability Feature for Maven, pypi, golang, and npm ecosystems.

Ignore vulnerabilities feature for CLI

---

acceptance-tests/acceptance_tests_suite_test.go
cmd/root.go
pkg/analyses/summary/helpers.go
pkg/analyses/summary/types.go

Associated JIRA - [https://issues.redhat.com/browse/APPAI-2020](https://issues.redhat.com/browse/APPAI-2020)

Display snyk token info

---

README.md
cmd/root.go

Update readme with Ignore Vulnerability documentation

Update readme with Ignore Vulnerability documentation
